blueprint:
  name: Disable Zone
  description: disable motion
  domain: automation
  input:
    person:
      name: Person
      description: Select the person that needs to be home.
      selector:
        entity:
          domain: group
    zone:
      name: Zone
      description: Select the Zone the person needs to be in.
      selector:
        entity:
          domain: zone
    device:
      name: motion
      discription: device to input
      selector:
        entiy:
          domain: sensor
          
trigger:
  trigger:
    platform: zone
    entity_id: !input person
    zone: !input zone
    # Event is either enter or leave
    event: leave
mode: single
action: 
    - entity_id: !input device
      service: homeassistant.turn_off
