blueprint:
  name: Disable automation
  description: >
     Disable automation when someone leaves. Up to 5 users. If you don't have 5 users re-select a user.
  domain: automation
  input:
    personone:
      name: Person
      description: Select the person first that needs to be home.
      selector:
        entity:
          domain: person
    persontwo:
      name: Person
      description: Select the second person that needs to be home.
      selector:
        entity:
          domain: person
    personthree:
      name: Person
      description: Select the third person that needs to be home.
      selector:
        entity:
          domain: person
    personfour:
      name: Person
      description: Select the fourth person that needs to be home.
      selector:
        entity:
          domain: person
    personfive:
      name: Person
      description: Select the fith person that needs to be home.
      selector:
        entity:
          domain: person
    zone:
      name: Zone
      description: Select the Zone the person needs to be in.
      default: zone.home
      selector:
          entity:
            domain: zone
    automation: 
      name: Automation
      description: Select theautomation that needs to be muted.
      selector:
        entity:
          domain: automation
trigger:
  - platform: zone
    entity_id: !input personone
    zone: !input zone
    event: leave
  - platform: zone
    entity_id: !input persontwo
    zone: !input zone
    event: leave
  - platform: zone
    entity_id: !input personthree
    zone: !input zone
    event: leave
  - platform: zone
    entity_id: !input personfour
    zone: !input zone
    event: leave
  - platform: zone
    entity_id: !input personfive
    zone: !input zone
    event: leave
    
  condition:
    - condition: state
      entity_id: personone
      state: AWAY
    - condition: state
      entity_id: persontwo
      state: AWAY
    - condition: state
      entity_id: persontwo
      state: AWAY
    - condition: state
      entity_id: personthree
      state: AWAY
    - condition: state
      entity_id: personfour
      state: AWAY
    - condition: state
      entity_id: personfive
      state: AWAY
action:
  action:
  - service: automation.turn_off
    data: {}
    entity_id: !input automation
