blueprint:
  name: Disable automation
  description: >
     Disable automation when someone leaves. Up to 5 users. If you don't have 5 users re-select a user.
  domain: automation
  input:
    personone:
      name: Person
      description: Select the person first that needs to be home.
      selector:
        entity:
          domain: person
    persontwo:
      name: Person
      description: Select the second person that needs to be home.
      selector:
        entity:
          domain: person
    personthree:
      name: Person
      description: Select the third person that needs to be home.
      selector:
        entity:
          domain: person
    personfour:
      name: Person
      description: Select the fourth person that needs to be home.
      selector:
        entity:
          domain: person
    personfive:
      name: Person
      description: Select the fith person that needs to be home.
      selector:
        entity:
          domain: person
    zone:
      name: Zone
      description: Select the Zone the person needs to be in.
      default: zone.home
      selector:
          entity:
            domain: zone
    automation: 
      name: Automation
      description: Select theautomation that needs to be muted.
      selector:
        entity:
          domain: automation
trigger:
  - platform: zone
    entity_id: !input personone
    zone: zone.home
    event: leave
  - platform: zone
    entity_id: !input persontwo
    zone: zone.home
    event: leave
  - platform: zone
    entity_id: !input personthree
    zone: zone.home
    event: leave
  - platform: zone
    entity_id: !input personfour
    zone: zone.home
    event: leave
  - platform: zone
    entity_id: !input personfive
    zone: zone.home
    event: leave
  condition:
    - condition: state
      entity_id: 
      state: AWAY
    - condition: state
      entity_id: !input persontwo
      state: AWAY
    - condition: state
      entity_id: !input persontwo
      state: AWAY
    - condition: state
      entity_id: !input personthree
      state: AWAY
    - condition: state
      entity_id: !input personfour
      state: AWAY
    - condition: state
      entity_id: !input personfive
      state: AWAY
action:
  action:
  - service: automation.turn_off
    data: {}
    entity_id: !input automation
  - wait_for_trigger:
    - platform: zone
      entity_id: !input personone
      zone: zone.home
      event: event
    - platform: zone
      entity_id: !input persontwo
      zone: zone.home
      event: enter
    - platform: zone
      entity_id: !input personthree
      zone: zone.home
      event: enter
    - platform: zone
      entity_id: !input personfour
      zone: zone.home
      event: enter
    - platform: zone
      entity_id: !input personfive
      zone: zone.home
      event: enter
  - service: automation.turn_on
    data: {}
    entity_id: !input automation
