blueprint:
  name: Disable Zone
  description: disable motion
  domain: automation
  input:
    person:
      name: Person
      description: Select the person that needs to be home.
      selector:
        entity:
          domain: group
    zone:
      name: Zone
      description: Select the Zone the person needs to be in.
      selector:
        entity:
          domain: zone
    device:
      name: sensor
      discription: Sensor to turn off
      selector:
        entity:
          domain: sensor
trigger:
   platform: zone
   entity_id: !input person
   zone: !input zone
    # Event is either enter or leave
    event: leave
mode: single
action: 
  - service: homeassistant.turn_off
    target: !input device
