blueprint:
  name: Disable automation when a person leaves.
  description: disable motion
  domain: automation
  input:
    one:
      name: person
      description: Select the person 1 that needs to be home.
      selector:
        entity:
          domain: person
    zone:
      name: Zone
      description: Select the Zone the person needs to be in.
      default: zone.home
      selector:
          entity:
            domain: zone
     automation:
      name: automation
      discription: automation to turn off
      selector:
        entity:
          domain: automation
          
  trigger:
  - platform: zone
    entity_id: !input one
    zone: !input zone
    event: enter
  condition: []
  action:
  - service: automation.turn_off
    data: {}
    entity_id: !input automation
