blueprint:
  name: Disable Zone
  description: disable motion
  domain: automation
  input:
    person:
      name: Person
      description: Select the person that needs to be home.
      selector:
        entity:
          domain: person
    zone:
      name: Zone
      description: Select the Zone the person needs to be in.
      selector:
        entity:
          domain: zone
    sensor:
      name: Sensor
      discription: Sensor
      selector:
        entiy:
          domain: sensor
          device_class: illuminance
trigger:
  trigger:
    platform: zone
    entity_id: !input person
    zone: !input zone
    # Event is either enter or leave
    event: leave
#trigger: 
#    platform: state
#    entity_id: !input sensor
#    to: 'off'

action: 
    - entity_id: !input sensor
      service: homeassistant.turn_off
