blueprint:
  name: Disable Zone
  description: disable motion
  domain: automation
  input:
    person:
      name: Person
      description: Select the person that needs to be home.
      selector:
        entity:
          domain: person
    zone:
      name: Zone
      description: Select the Zone the person needs to be in.
      default: zone.home
      selector:
          entity:
            domain: zone
    device:
      name: sensor
      discription: Sensor to turn off
      selector:
        entity:
          domain: sensor
trigger:
  - platform: state
    entity_id: !input zone
    from: "home"
    to: "away"
mode: single
action: 
  - service: homeassistant.turn_off
    target: !input device
