blueprint:
  name: Disable automation
  description: >
     Disable automation when someone leaves
  domain: automation
  input:
    person:
      name: Person
      description: Select the person that needs to be home.
      selector:
        entity:
          domain: person
    zone:
      name: Zone
      description: Select the Zone the person needs to be in.
      default: zone.home
      selector:
          entity:
            domain: zone
    automation: 
      name: Automation
      description: Select theautomation that needs to be muted.
      selector:
        entity:
          domain: automation

trigger:
  - platform: state
    entity_id: !input person
    to: "away"
action:
  action:
  - service: automation.turn_off
    data: {}
    entity_id: !input automation
