blueprint:
  name: Disable automation
  description: >
     Disable automation when someone leaves. Up to 5 users. If you don't have 5 users re-select a user.
     The automation will wait for one of the five people to come homw
  domain: automation
  input:
    personone:
      name: Person
      description: Select the person first that needs to be home.
      selector:
        entity:
          domain: person
    persontwo:
      name: Person
      description: Select the second person that needs to be home.
      selector:
        entity:
          domain: person
    personthree:
      name: Person
      description: Select the third person that needs to be home.
      selector:
        entity:
          domain: person
    personfour:
      name: Person
      description: Select the fourth person that needs to be home.
      selector:
        entity:
          domain: person
    personfive:
      name: Person
      description: Select the fith person that needs to be home.
      selector:
        entity:
          domain: person
    zone:
      name: Zone
      description: Select the Zone the person needs to be in.
      default: zone.home
      selector:
          entity:
            domain: zone
    automation: 
      name: Automation
      description: Select theautomation that needs to be muted.
      selector:
        entity:
          domain: automation
    timestart:
      name: timestart
      description: Select a start time. One must be selected even if its only runs one second format is xx:xx:xx
      selector:
        entity: timestart
    timeend:
      name: timeend
      discription: End time. See note above
      selector:
        entity: timeend
trigger:
  - platform: state
    entity_id: !input personone
    to: "away"
  - platform: state
    entity_id: !input persontwo
    to: "away"
  - platform: state
    entity_id: !input personthree
    to: "away"
  - platform: state
    entity_id: !input personfour
    to: "away"
  - platform: state
    entity_id: !input personfive
    to: "away"
  - platform: time
    at: !input timestart
condtion:
  - condition: state
    entity_id: !input personone
    state: AWAY
  - condition: state
    entity_id: !input personone
    state: AWAY
  - condition: state
    entity_id: !input personone
    state: AWAY
  - condition: state
    entity_id: !input personone
    state: AWAY
  - condition: state
    entity_id: !input personone
    state: AWAY 
  - condition:
      - platform: time
    at: !input timestart
action:
  - service: automation.turn_off
    data: {}
    entity_id: !input automation
  - wait_for_trigger:
    - platform: zone
      entity_id: !input personone
      zone: !input zone
      event: enter
    - platform: zone
      entity_id: !input persontwo
      zone: zone.home
      event: enter
    - platform: zone
      entity_id: !input personthree
      zone: !input zone
      event: enter
    - platform: zone
      entity_id: !input personfour
      zone: !input zone
      event: enter
    - platform: zone
      entity_id: !input personfive
      zone: !input zone
      event: enter
    - platform: time
      at: !input timeend
  - service: automation.turn_on
    data: {}
    entity_id: !input automation
